/*
 * Copyright 2022 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */
#define PCR_SRE_sre1 0x01u /*!<@brief Slew Rate Enable: Slow */

/*! @name PORT3_18 (coord K16), SMARTDMA_DEBUG
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SMARTDMA_DEBUG_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SMARTDMA_DEBUG_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SMARTDMA_DEBUG_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*! @name PORT2_10 (coord M3), SMARTDMA_DEBUG_1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SMARTDMA_DEBUG_1_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SMARTDMA_DEBUG_1_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SMARTDMA_DEBUG_1_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PORT1_5 (coord B3), SMARTDMA_DEBUG_2
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SMARTDMA_DEBUG_2_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SMARTDMA_DEBUG_2_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SMARTDMA_DEBUG_2_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PORT1_4 (coord A4), SMARTDMA_DEBUG_3
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SMARTDMA_DEBUG_3_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SMARTDMA_DEBUG_3_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SMARTDMA_DEBUG_3_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PORT4_22 (coord T12), ARM_DEBUG_IO1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ARM_DEBUG_IO1_GPIO GPIO4                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_ARM_DEBUG_IO1_GPIO_PIN 22U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_ARM_DEBUG_IO1_GPIO_PIN_MASK (1U << 22U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ARM_DEBUG_IO1_PORT PORT4                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ARM_DEBUG_IO1_PIN 22U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ARM_DEBUG_IO1_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORT4_15 (coord T8), TO_IO
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_TO_IO_PORT PORT4                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_TO_IO_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_TO_IO_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORT3_16 (coord J15), MDIO
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MDIO_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MDIO_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MDIO_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORT3_20 (coord M17), MDC
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MDC_GPIO_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_MDC_GPIO_GPIO_PIN 20U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_MDC_GPIO_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MDC_GPIO_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MDC_GPIO_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MDC_GPIO_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
