/*
 * Copyright 2022 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v16.0
processor: MCXN947
package_id: MCXN947VDF
mcu_data: ksdk2_0
processor_version: 16.3.0
external_user_signals: {}
pin_labels:
- {pin_num: K16, pin_signal: PIO3_18/FC6_P6/CT2_MAT0/PWM1_X0/FLEXIO0_D26/EZH_PIO18/SAI1_RX_BCLK, label: SMARTDMA_DEBUG, identifier: EZH_DEBUG;SMARTDMA_DEBUG}
- {pin_num: A4, pin_signal: PIO1_4/WUU0_IN8/FREQME_CLK_IN0/FC3_P4/FC5_P0/CT1_MAT2/SCT0_OUT0/FLEXIO0_D12/EZH_PIO0/ENET0_TX_CLK/SAI0_TXD1/TSI0_CH4/ADC0_A20/CMP0_IN2,
  label: SMARTDMA_DEBUG_3, identifier: MDIO;SMARTDMA_DEBUG_1;SMARTDMA_DEBUG_3}
- {pin_num: B11, pin_signal: PIO0_11/CT0_MAT1/FLEXIO0_D3/HSCMP2_OUT/ADC0_B11, label: MDC, identifier: MDC}
- {pin_num: D2, pin_signal: PIO1_12/WUU0_IN12/TRACE_CLK/FC4_P4/FC3_P0/CT2_MAT2/SCT0_OUT4/FLEXIO0_D20/EZH_PIO8/PLU_OUT2/ENET0_RXER/CAN1_RXD/TSI0_CH21/ADC1_A12, label: MDIO,
  identifier: MDIO}
- {pin_num: J15, pin_signal: PIO3_16/FC8_P2/CT_INP8/PWM1_A2/FLEXIO0_D24/EZH_PIO16/SIM0_CLK/SAI1_TX_BCLK, label: MDIO, identifier: MDIO}
- {pin_num: B10, pin_signal: PIO0_16/WUU0_IN2/FC0_P0/CT0_MAT0/UTICK_CAP2/FLEXIO0_D0/PDM0_CLK/I3C0_SDA/TSI0_CH11/ADC0_A8, label: TO_IO, identifier: TO_IO}
- {pin_num: T8, pin_signal: PIO4_15/WUU0_IN21/TRIG_OUT4/USB1_VBUS_DIG/CT4_MAT3/FLEXIO0_D23/PLU_OUT3/SINC0_MCLK_OUT0/CAN1_RXD/OPAMP0_OUT/ADC0_A1/CMP0_IN4P, label: TO_IO,
  identifier: TO_IO}
- {pin_num: C6, pin_signal: PIO1_0/WUU0_IN6/LPTMR0_ALT3/TRIG_IN0/FC3_P0/FC4_P4/CT_INP4/SCT0_OUT6/FLEXIO0_D8/SAI1_TX_BCLK/TSI0_CH0/ADC0_A16/CMP0_IN0, label: MDC_GPIO,
  identifier: MDC_GPIO}
- {pin_num: M3, pin_signal: PIO2_10/TRACE_DATA2/SCT0_IN4/PWM1_X2/FLEXIO0_D18/EZH_PIO31/FLEXSPI0_B_DATA6/SINC0_MCLK4/SAI1_RXD1, label: SMARTDMA_DEBUG_1, identifier: SMARTDMA_DEBUG_2;SMARTDMA_DEBUG_1}
- {pin_num: T12, pin_signal: PIO4_22/CT2_MAT2/FLEXIO0_D30, label: ARM_DEBUG_IO1, identifier: ARM_DEBUG_IO1}
- {pin_num: M17, pin_signal: PIO3_20/WUU0_IN27/TRIG_OUT0/FC8_P4/FC6_P0/CT2_MAT2/PWM1_A3/FLEXIO0_D28/EZH_PIO20/SIM0_PD/SAI1_TXD0, label: MDC, identifier: MDC_GPIO}
- {pin_num: K2, pin_signal: PIO2_6/TRIG_IN4/FC9_P4/SDHC0_D3/SCT0_OUT4/PWM1_A0/FLEXIO0_D14/EZH_PIO26/FLEXSPI0_B_DATA2/SINC0_MCLK2/SAI0_TX_BCLK, label: MDC_TRIG_IN,
  identifier: MDC_TRIG_IN}
- {pin_num: K5, pin_signal: PIO1_20/TRIG_IN2/FC5_P4/FC4_P0/CT3_MAT2/SCT0_OUT8/FLEXIO0_D28/EZH_PIO16/PLU_OUT6/ENET0_MDC/CAN1_TXD/ADC1_A20/CMP1_IN3, label: SCT0_OUT8,
  identifier: SCT0_OUT8}
- {pin_num: H3, pin_signal: PIO2_2/WUU0_IN16/CLKOUT/FC9_P3/SDHC0_D1/SCT0_OUT0/PWM1_A2/FLEXIO0_D10/EZH_PIO22/FLEXSPI0_B_SS0_b/SINC0_MCLK0/SAI0_TXD0, label: SCT0_OUT0,
  identifier: SCT0_OUT0}
- {pin_num: B17, pin_signal: PIO3_0/WUU0_IN22/TRIG_IN0/FC7_P3/CT_INP16/PWM0_A0/FLEXIO0_D8/EZH_PIO0/FLEXSPI0_A_SS0_b, label: MDIO_TRIG, identifier: MDIO_TRIG}
- {pin_num: G14, pin_signal: PIO3_5/FC7_P3/CT_INP19/PWM0_X3/FLEXIO0_D13/EZH_PIO5/SIM1_IO, label: MDIO_TRIG, identifier: MDIO_TRIG}
- {pin_num: B3, pin_signal: PIO1_5/FREQME_CLK_IN1/FC3_P5/FC5_P1/CT1_MAT3/SCT0_OUT1/FLEXIO0_D13/EZH_PIO1/ENET0_TXEN/SAI0_RXD1/TSI0_CH5/ADC0_A21/CMP0_IN3, label: SMARTDMA_DEBUG_2,
  identifier: SMARTDMA_DEBUG_1;SMARTDMA_DEBUG_2}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: A1, peripheral: LP_FLEXCOMM4, signal: LPFLEXCOMM_P0, pin_signal: PIO1_8/WUU0_IN10/LPTMR1_ALT3/TRACE_DATA0/FC4_P0/FC5_P4/CT_INP8/SCT0_OUT2/FLEXIO0_D16/EZH_PIO4/PLU_OUT0/ENET0_TXD2/I3C1_SDA/TSI0_CH17/ADC1_A8,
    slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, passive_filter: disable, pull_value: low, input_buffer: enable,
    invert_input: normal}
  - {pin_num: B1, peripheral: LP_FLEXCOMM4, signal: LPFLEXCOMM_P1, pin_signal: PIO1_9/TRACE_DATA1/FC4_P1/FC5_P5/CT_INP9/SCT0_OUT3/FLEXIO0_D17/EZH_PIO5/PLU_OUT1/ENET0_TXD3/I3C1_SCL/TSI0_CH18/ADC1_A9,
    slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, passive_filter: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: K16, peripheral: SMARTDMA0, signal: 'SMARTDMA_PIO, 18', pin_signal: PIO3_18/FC6_P6/CT2_MAT0/PWM1_X0/FLEXIO0_D26/EZH_PIO18/SAI1_RX_BCLK, identifier: SMARTDMA_DEBUG}
  - {pin_num: M3, peripheral: SMARTDMA0, signal: 'SMARTDMA_PIO, 31', pin_signal: PIO2_10/TRACE_DATA2/SCT0_IN4/PWM1_X2/FLEXIO0_D18/EZH_PIO31/FLEXSPI0_B_DATA6/SINC0_MCLK4/SAI1_RXD1,
    identifier: SMARTDMA_DEBUG_1}
  - {pin_num: B3, peripheral: SMARTDMA0, signal: 'SMARTDMA_PIO, 1', pin_signal: PIO1_5/FREQME_CLK_IN1/FC3_P5/FC5_P1/CT1_MAT3/SCT0_OUT1/FLEXIO0_D13/EZH_PIO1/ENET0_TXEN/SAI0_RXD1/TSI0_CH5/ADC0_A21/CMP0_IN3,
    identifier: SMARTDMA_DEBUG_2}
  - {pin_num: A4, peripheral: SMARTDMA0, signal: 'SMARTDMA_PIO, 0', pin_signal: PIO1_4/WUU0_IN8/FREQME_CLK_IN0/FC3_P4/FC5_P0/CT1_MAT2/SCT0_OUT0/FLEXIO0_D12/EZH_PIO0/ENET0_TX_CLK/SAI0_TXD1/TSI0_CH4/ADC0_A20/CMP0_IN2,
    identifier: SMARTDMA_DEBUG_3}
  - {pin_num: T12, peripheral: GPIO4, signal: 'GPIO, 22', pin_signal: PIO4_22/CT2_MAT2/FLEXIO0_D30, direction: OUTPUT, gpio_init_state: 'false'}
  - {pin_num: T8, peripheral: CTIMER4, signal: 'MATCH, 3', pin_signal: PIO4_15/WUU0_IN21/TRIG_OUT4/USB1_VBUS_DIG/CT4_MAT3/FLEXIO0_D23/PLU_OUT3/SINC0_MCLK_OUT0/CAN1_RXD/OPAMP0_OUT/ADC0_A1/CMP0_IN4P}
  - {pin_num: J15, peripheral: SMARTDMA0, signal: 'SMARTDMA_PIO, 16', pin_signal: PIO3_16/FC8_P2/CT_INP8/PWM1_A2/FLEXIO0_D24/EZH_PIO16/SIM0_CLK/SAI1_TX_BCLK, slew_rate: slow,
    input_buffer: enable}
  - {pin_num: M17, peripheral: GPIO3, signal: 'GPIO, 20', pin_signal: PIO3_20/WUU0_IN27/TRIG_OUT0/FC8_P4/FC6_P0/CT2_MAT2/PWM1_A3/FLEXIO0_D28/EZH_PIO20/SIM0_PD/SAI1_TXD0,
    direction: INPUT, gpio_per_interrupt: kGPIO_ActiveHighTriggerOutputEnable, eft_interrupt: enable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Enables the clock for GPIO3: Enables clock */
    CLOCK_EnableClock(kCLOCK_Gpio3);
    /* Enables the clock for GPIO4: Enables clock */
    CLOCK_EnableClock(kCLOCK_Gpio4);
    /* Enables the clock for PORT1: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port1);
    /* Enables the clock for PORT2: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port2);
    /* Enables the clock for PORT3: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port3);
    /* Enables the clock for PORT4: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port4);

    gpio_pin_config_t MDC_GPIO_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_20 (pin M17)  */
    GPIO_PinInit(BOARD_INITPINS_MDC_GPIO_GPIO, BOARD_INITPINS_MDC_GPIO_PIN, &MDC_GPIO_config);

    gpio_pin_config_t ARM_DEBUG_IO1_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO4_22 (pin T12)  */
    GPIO_PinInit(BOARD_INITPINS_ARM_DEBUG_IO1_GPIO, BOARD_INITPINS_ARM_DEBUG_IO1_PIN, &ARM_DEBUG_IO1_config);

    /* Interrupt configuration on GPIO3_20 (pin M17): Enable active high-trigger output */
    GPIO_SetPinInterruptConfig(BOARD_INITPINS_MDC_GPIO_GPIO, BOARD_INITPINS_MDC_GPIO_PIN, kGPIO_ActiveHighTriggerOutputEnable);

    /* PORT1_4 (pin A4) is configured as EZH_PIO0 */
    PORT_SetPinMux(BOARD_INITPINS_SMARTDMA_DEBUG_3_PORT, BOARD_INITPINS_SMARTDMA_DEBUG_3_PIN, kPORT_MuxAlt7);

    PORT1->PCR[4] = ((PORT1->PCR[4] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_5 (pin B3) is configured as EZH_PIO1 */
    PORT_SetPinMux(BOARD_INITPINS_SMARTDMA_DEBUG_2_PORT, BOARD_INITPINS_SMARTDMA_DEBUG_2_PIN, kPORT_MuxAlt7);

    PORT1->PCR[5] = ((PORT1->PCR[5] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    const port_pin_config_t port1_8_pinA1_config = {/* Internal pull-up/down resistor is disabled */
                                                    .pullSelect = kPORT_PullDisable,
                                                    /* Low internal pull resistor value is selected. */
                                                    .pullValueSelect = kPORT_LowPullResistor,
                                                    /* Fast slew rate is configured */
                                                    .slewRate = kPORT_FastSlewRate,
                                                    /* Passive input filter is disabled */
                                                    .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                                    /* Open drain output is disabled */
                                                    .openDrainEnable = kPORT_OpenDrainDisable,
                                                    /* Low drive strength is configured */
                                                    .driveStrength = kPORT_LowDriveStrength,
                                                    /* Pin is configured as FC4_P0 */
                                                    .mux = kPORT_MuxAlt2,
                                                    /* Digital input enabled */
                                                    .inputBuffer = kPORT_InputBufferEnable,
                                                    /* Digital input is not inverted */
                                                    .invertInput = kPORT_InputNormal,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    .lockRegister = kPORT_UnlockRegister};
    /* PORT1_8 (pin A1) is configured as FC4_P0 */
    PORT_SetPinConfig(PORT1, 8U, &port1_8_pinA1_config);

    const port_pin_config_t port1_9_pinB1_config = {/* Internal pull-up/down resistor is disabled */
                                                    .pullSelect = kPORT_PullDisable,
                                                    /* Low internal pull resistor value is selected. */
                                                    .pullValueSelect = kPORT_LowPullResistor,
                                                    /* Fast slew rate is configured */
                                                    .slewRate = kPORT_FastSlewRate,
                                                    /* Passive input filter is disabled */
                                                    .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                                    /* Open drain output is disabled */
                                                    .openDrainEnable = kPORT_OpenDrainDisable,
                                                    /* Low drive strength is configured */
                                                    .driveStrength = kPORT_LowDriveStrength,
                                                    /* Pin is configured as FC4_P1 */
                                                    .mux = kPORT_MuxAlt2,
                                                    /* Digital input enabled */
                                                    .inputBuffer = kPORT_InputBufferEnable,
                                                    /* Digital input is not inverted */
                                                    .invertInput = kPORT_InputNormal,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    .lockRegister = kPORT_UnlockRegister};
    /* PORT1_9 (pin B1) is configured as FC4_P1 */
    PORT_SetPinConfig(PORT1, 9U, &port1_9_pinB1_config);

    /* PORT2_10 (pin M3) is configured as EZH_PIO31 */
    PORT_SetPinMux(BOARD_INITPINS_SMARTDMA_DEBUG_1_PORT, BOARD_INITPINS_SMARTDMA_DEBUG_1_PIN, kPORT_MuxAlt7);

    PORT2->PCR[10] = ((PORT2->PCR[10] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* EFT detect interrupts configuration on PORT3_ */
    PORT_EnableEFTDetectInterrupts(PORT3, 0x100000u);

    /* PORT3_16 (pin J15) is configured as EZH_PIO16 */
    PORT_SetPinMux(BOARD_INITPINS_MDIO_PORT, BOARD_INITPINS_MDIO_PIN, kPORT_MuxAlt7);

    PORT3->PCR[16] = ((PORT3->PCR[16] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_SRE_MASK | PORT_PCR_IBE_MASK)))

                      /* Slew Rate Enable: Slow. */
                      | PORT_PCR_SRE(PCR_SRE_sre1)

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_18 (pin K16) is configured as EZH_PIO18 */
    PORT_SetPinMux(BOARD_INITPINS_SMARTDMA_DEBUG_PORT, BOARD_INITPINS_SMARTDMA_DEBUG_PIN, kPORT_MuxAlt7);

    PORT3->PCR[18] = ((PORT3->PCR[18] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_20 (pin M17) is configured as PIO3_20 */
    PORT_SetPinMux(BOARD_INITPINS_MDC_GPIO_PORT, BOARD_INITPINS_MDC_GPIO_PIN, kPORT_MuxAlt0);

    PORT3->PCR[20] = ((PORT3->PCR[20] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT4_15 (pin T8) is configured as CT4_MAT3 */
    PORT_SetPinMux(BOARD_INITPINS_TO_IO_PORT, BOARD_INITPINS_TO_IO_PIN, kPORT_MuxAlt4);

    PORT4->PCR[15] = ((PORT4->PCR[15] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT4_22 (pin T12) is configured as PIO4_22 */
    PORT_SetPinMux(BOARD_INITPINS_ARM_DEBUG_IO1_PORT, BOARD_INITPINS_ARM_DEBUG_IO1_PIN, kPORT_MuxAlt0);

    PORT4->PCR[22] = ((PORT4->PCR[22] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
